[package]
name = "generate-blogs"
version = "0.1.0"
edition = "2024"

[dependencies]
markdown = "*"
chrono = "*"
rss-gen = "*"
atom_syndication = "*"
image = "*"
rayon = "*"

[profile.dev.package.image]
opt-level = 3

[profile.dev.package.rayon]
opt-level = 3